site:
  title: Bibliomation Internship Guide
  url: https://bibliomation-inc.github.io/internship
  start_page: docs::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    # Load UI from a local bundle to avoid network downloads
    url: ./ui-bundle.zip
    snapshot: false
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll

output:
  dir: build/site

runtime:
  fetch: false

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true